### ISSUE TITLE
gridjs-angular update to gridjs v6

### ISSUE THREAD

**Issue by jure123** [grid-js/gridjs-angular#180]
gridjs-angular currently only supports gridjs v4. Is this going to be updated to v6 anytime soon?

**Comment by chrisweight** [comment]
feels like this repo is dead, sadly :(

**Comment by jure123** [comment]
I found out that it's quite easy to use the native gridjs lib on Angular enviroment:

In html template add container for the grid:
`<div #grid1></div>`

In TS component code initialize the grid:

```
import { Gridh } from "gridjs";

export class CommonUI_TablesComponent implements AfterViewInit {

  @ViewChild("grid1") grid1;
  
  ngAfterViewInit(): void {
      new Grid({
        sort: true,
        pagination: true,
        search: true,
        columns: [{ id: "name", name: 'Name'}, { id: "email", name: 'Email' }, { id: "phone", name: "Phone" }],
        data: this.getData()
      }).render(this.grid1.nativeElement);
  }
}
```

That's it.

**Comment by DominicWrege** [comment]
any updates?

**Comment by salamaashoush** [comment]
I plan to revive this repo

**Comment by joeskeen** [comment]
@salamaashoush do you need any help? I'd be glad to be of assistance. It would be better for me to contribute here rather than spend my time working on an alternative.

**Comment by joeskeen** [comment]
@salamaashoush I see you :+1: my last message - any direction on what I can do to help? I cloned the repo and tried running various commands, but I'm having trouble running anything. There aren't a lot of docs in the README on how to work with this code base - any pointers you can give me? Full disclosure I have TONS of experience with Angular, but not with NX, Storybook, Cypress... I want to tinker around and get things working but I'm trying to be cautious and not break anything.

The main objectives I see as needing to be done (aside from anything NX/Storybook/Cypress related):

* Upgrade dependencies on Angular to latest (v17.1)
* Upgrade dependencies on GridJS to latest (v6.1)
* Ensure everything works with latest Node.JS
* Improve documentation (so future contributors know where to begin)

Outstanding questions: 

* GridJS depends on preact. Is that an issue? (I have little React experience)
* What test cases (unit/integration/e2e) are important to this project? I saw only one unit test, and it was failing as it wasn't set up correctly (just the auto-generated Angular CLI component spec).
* Are there any features of GridJS that are new since the last time this was touched, which we will need to expose through the Angular layer?
* Is there anything in the project that is just noise that we could do without to allow for a more focused repository?

I'm sure I'll have more questions as I get deeper into this.

**Comment by salamaashoush** [comment]
@joeskeen, thank you for reaching out and showing interest in enhancing the repository. Your willingness to contribute is greatly appreciated. I have good news: I've recently updated the repository to ensure compatibility with the latest versions of Angular and GridJS, and your contributions would be most welcome. The changes have been merged in [this pull request](https://github.com/grid-js/gridjs-angular/pull/181), so you should be able to pull the latest version and get started on testing and further improvements.

**Here are a few areas where your expertise could be especially valuable:**

1. **Application Testing**: Utilize the demo application within the repository to test various configurations and datasets. You can start the demo app using the command `pnpm dev`, yes the repo uses `pnpm` now.
2. **Unit Testing**: There's a need for more unit tests. Your experience could greatly improve our testing coverage.
3. **Angular Wrapper Enhancements**: Consider enhancing the Angular wrapper, potentially by integrating signals for a more reactive approach. The wrapper is currently functional with GridJS 6, based on the previous version, but there's room for improvement.

**Regarding your inquiries:**

- Upgrading Angular and GridJS to their latest versions, ensuring compatibility with the latest Node.js (DONE),  and improving documentation are all key objectives, I could use your help to write more docs and update the gridjs docs site
- Concerning GridJS's dependency on Preact, it shouldn't pose a major issue. However, if you have specific concerns or encounter challenges, I'm here to assist.
- In terms of testing, both unit and integration tests are crucial. We should aim to cover key functionalities and ensure the wrapper integrates smoothly with GridJS features.
- As for new GridJS features since the last update, since I am not actively working on Angular or GridJS projects now, it would be great if you could check if something is missing and implement it.
- Streamlining the project by removing unnecessary elements, now the repo only contains a basic NX setup with a demo app to make it easier for testing and publishing. I chose NX for its scalability and ease of use.

Your further questions and contributions are eagerly awaited. Let's collaborate to make this project even better.

**Comment by joeskeen** [comment]
OK @salamaashoush since the original issue is completed, should we close this issue and open separate issues for the areas needing help from your description above?

**Comment by joeskeen** [comment]
While waiting for merge, if anyone wants to use the updated version I have worked on you can `npm i github:joeskeen/gridjs-angular#pr-182`. I'm not planning to delete this branch until it is part of an official release.

**Comment by salamaashoush** [comment]
V2 is live on npm https://www.npmjs.com/package/gridjs-angular it includes the gridjs v6 upgrade https://github.com/grid-js/gridjs-angular/releases/tag/2.0.0
